parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Psr\Container\ContainerInterface $weatherFetchers: !tagged_locator {tag: 'app.weather.fetcher', default_index_method: getPlace }
            iterable $weatherFetchers2: !tagged_iterator {tag: 'app.weather.fetcher' }

    _instanceof:
        App\Weather\Fetcher\FetcherInterface:
            tags: ['app.weather.fetcher']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/**/Model/'
